"""add performance_metrics to jobs

Revision ID: 82ef48fc3c57
Revises: d4f1b0c7a2e1
Create Date: 2026-02-14 00:17:51.504358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ef48fc3c57'
down_revision: Union[str, Sequence[str], None] = 'd4f1b0c7a2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_ledger_created_at'), 'credit_ledger', ['created_at'], unique=False)
    op.add_column('jobs', sa.Column('performance_metrics', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_jobs_user_idempotency'), table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_user_idempotency'), 'jobs', ['user_id', 'idempotency_key'], unique=1)
    op.drop_column('jobs', 'performance_metrics')
    op.drop_index(op.f('ix_credit_ledger_created_at'), table_name='credit_ledger')
    # ### end Alembic commands ###
