"""Add intelligence and QC columns to jobs

Revision ID: f89cfc8f9762
Revises: 59c6f99193a2
Create Date: 2026-02-10 09:29:34.818811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89cfc8f9762'
down_revision: Union[str, Sequence[str], None] = '59c6f99193a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('media_intelligence', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('qc_result', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('director_plan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'director_plan')
    op.drop_column('jobs', 'qc_result')
    op.drop_column('jobs', 'media_intelligence')
    # ### end Alembic commands ###
